name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    name: Maven Setup
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Setup Project
        run: mvn clean install dependency:tree -DskipTests

  build:
    needs: setup
    strategy:
      matrix:
        java-version: [8, 11, 16, 17, 18, 19]

    runs-on: ubuntu-latest
    name: Build Java ${{ matrix.java-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Build Project
        run: mvn clean package -Dmaven.javadoc.skip=true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy JavaDocs
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Project
        run: mvn package -DskipTests

      - name: Build JavaDocs
        run: bash javadoc.sh ${GITHUB_SHA::7}